#!/usr/bin/env python
# encoding: utf-8
# Marcus Meng 2009

# 1. A simple program
bld.new_task_gen(
	features = 'cc cprogram',
	source = bld.path.ant_glob('*.c'),
	target = 'atelier',
	uselib_local = '',
	includes = '. /usr/include')

