; For testing, you might want to change the values of your numbers where
; num1 is the 16-bit first number
; num2 is the 16-bit second number
; num1_h, num1_l, num2_h, num2_l are described below
;
; Please DO NOT change the labels num1_h, num1_l, etc... or your program
; would not compile. I am planning to include my own test data and will
; not be editing your code.

; Example: If num1 = Hex 1234 and num2 = Hex 5678
; then:

;--------------- initialize test data ----------
num1_h	equ	0x12	; higher byte of the first number
num1_l	equ	0x34	; lower byte of the first number
num2_h	equ	0x56	; higher byte of the second number
num2_l	equ	0x78	; lower byte of the second number

; For testing, you might want to choose your own 16-bit numbers
